services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/sites
    networks:
      - app-network
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - database
    working_dir: /var/www/sites
    command: sh -c "php-fpm && composer install"


  database:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.27.2
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/sites
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
